### ISSUE TITLE
Any chance this could be updated to work on the latest version of the game?

### ISSUE THREAD

**Issue by ZeroCool940711** [LickIt/chronicon-stash-editor#1]
I know this repository and code is a few years old but is there any chance this could be updated to work with the latest version of the game?, when I try to run it `_player.stash` loads but its completely empty and `player.stash` doesn't load and throws the following error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Python\lib\encodings\hex_codec.py", line 19, in hex_decode
    return (binascii.a2b_hex(input), len(input))
binascii.Error: Non-hexadecimal digit found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:\Games\Chronicon\chronicon-stash-editor-master\stash_editor.py", line 105, in load_file
    stash = Stash(fname)
  File "D:\Games\Chronicon\chronicon-stash-editor-master\decoder.py", line 95, in __init__
    self.read(f.read())
  File "D:\Games\Chronicon\chronicon-stash-editor-master\decoder.py", line 98, in read
    _string = self.read_header(_string)
  File "D:\Games\Chronicon\chronicon-stash-editor-master\decoder.py", line 111, in read_header
    codecs.decode(_string[i:i + 8], "hex"))
binascii.Error: decoding with 'hex' codec failed (Error: Non-hexadecimal digit found)
```

**Comment by LickIt** [comment]
Sorry, I don't have the time to fix it now.
If I replay the game I might revisit it in the future.

**Comment by ZeroCool940711** [comment]
I understand, it's a shame, I remember a few years ago when I first played Chronicon I used this stash editor and it was pretty cool, I downloaded the game again because of the recent updates with some interesting stuff and wanted to use the stash editor to save some time but I guess I will have to do some farming xD
